# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TorrentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.FileField(upload_to='upload_to=user_directory_path')),
                ('uploader', models.CharField(max_length=25)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
