# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentfile',
            name='location',
            field=models.FileField(upload_to='torrents/'),
        ),
    ]
